repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        args: [--line-length=120]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports==1.10.0 ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args: [ --py3-plus ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: ^tests/
