version: "3.8"

x-web:
  &x-web-common
  build:
    context: .
    dockerfile: ./deploy/web/Dockerfile
  environment:
    &x-web-environment
    SECRET_KEY: ${SECRET_KEY}
    DB_HOST: ${DB_HOST}
    DB_NAME: ${DB_NAME}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_USER: ${DB_USER}
    TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}

services:
  db:
    image: postgres:10
    container_name: postgres_db
    restart: always
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    <<: *x-web-common
    environment:
      <<: *x-web-environment
    container_name: web
    command: >
      bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --log-level debug --timeout 120 --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/code:cached
    depends_on:
      - db

  bot:
    <<: *x-web-common
    environment:
      <<: *x-web-environment
    depends_on:
      - web
