version: "3.8"

x-web:
  &x-web-common
  build:
    context: .
    dockerfile: ./deploy/web/Dockerfile
  restart: always
  environment:
    &x-web-environment
    SECRET_KEY: ${SECRET_KEY}
    DB_NAME: ${DB_NAME}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_USER: ${DB_USER}
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}
    TELEGRAM_API_ID: ${TELEGRAM_API_ID}
    TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    CLIENT_SESSION_SEARCH: ${CLIENT_SESSION_SEARCH}
    MAX_GROUPS_PER_USER: ${MAX_GROUPS_PER_USER}
    MAX_ANSWERS_PER_REQUEST: ${MAX_ANSWERS_PER_REQUEST}
    MAX_REQUESTS_PER_DAY: ${MAX_REQUESTS_PER_DAY}
services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  web:
    <<: *x-web-common
    environment:
      <<: *x-web-environment
    container_name: web
    command: >
      bash -c "python manage.py check && python manage.py migrate --noinput && python manage.py collectstatic --noinput && uvicorn config.asgi:application --reload-dir src --log-level debug --timeout 120 --bind 0.0.0.0:8000 --use-colors"
    ports:
      - "8000:8000"
    volumes:
      - .:/code:cached
    depends_on:
      - db
