# Generated by Django 4.1 on 2022-08-26 07:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="login",
            options={},
        ),
        migrations.RemoveField(
            model_name="login",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="login",
            name="id",
        ),
        migrations.RemoveField(
            model_name="login",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="login",
            name="client_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="tg_client.clientsession",
                verbose_name="Client Session",
            ),
        ),
    ]
