# Generated by Django 4.1 on 2022-08-29 13:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_client", "0002_alter_login_options_remove_login_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
    ]
