# Generated by Django 4.1 on 2022-08-29 13:39
from core.helpers import get_fixture
from django.db import migrations
from django.db import models


def load_fixture(apps, schema_editor):
    fixture_file = get_fixture("tg_client.json", "tg_client")

    fixture = open(fixture_file, "rb")
    from django.core import serializers

    objects = serializers.deserialize("json", fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    login = apps.get_model("tg_client", "Login")
    login.objects.all().delete()
    client_session = apps.get_model("tg_client", "ClientSession")
    client_session.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tg_client", "0002_alter_login_options_remove_login_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
