# Generated by Django 4.1 on 2022-08-25 08:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="QueryResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(help_text="query result", max_length=100)),
                ("message_date", models.DateField(blank=True, help_text="telegram message date", null=True)),
                ("from_user_id", models.IntegerField(help_text="message author id")),
                ("from_user_name", models.CharField(help_text="message author name", max_length=100)),
            ],
            options={
                "verbose_name": "Query Result",
                "verbose_name_plural": "Query Result",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(help_text="query string", max_length=100)),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Query",
            },
        ),
    ]
