# Generated by Django 4.1 on 2022-08-27 11:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_chattext_user_queryresult_query_userchat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, help_text="telegram user phone", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, help_text="telegram user first name", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, help_text="telegram user last name", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, help_text="telegram user name", max_length=150, null=True),
        ),
    ]
