# Generated by Django 4.1 on 2022-08-27 15:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_user_phone_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchat",
            name="name",
        ),
        migrations.AddField(
            model_name="userchat",
            name="chat_id",
            field=models.PositiveIntegerField(default=0, help_text="telegram chat id"),
        ),
        migrations.AddField(
            model_name="userchat",
            name="title",
            field=models.CharField(default="", help_text="telegram chat title", max_length=255),
        ),
        migrations.AddField(
            model_name="userchat",
            name="username",
            field=models.CharField(default="", help_text="telegram chat username", max_length=40),
        ),
    ]
