# Generated by Django 4.1 on 2022-08-29 13:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_remove_userchat_name_userchat_chat_id_userchat_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchquery",
            name="chat",
        ),
        migrations.AlterField(
            model_name="queryresult",
            name="message_date",
            field=models.DateTimeField(blank=True, help_text="telegram message date", null=True),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="queries", to="bot.user"),
        ),
    ]
