# Generated by Django 4.1 on 2022-08-29 13:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_remove_searchquery_chat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queryresult",
            name="from_user_name",
        ),
    ]
