# Generated by Django 4.1 on 2022-08-29 15:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_queryresult_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryresult",
            name="chat_username",
            field=models.CharField(default="", help_text="chat username", max_length=100),
        ),
    ]
