# Generated by Django 4.1 on 2022-08-31 10:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_queryresult_chat_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattext",
            name="name",
            field=models.CharField(help_text="name of text", max_length=200, unique=True),
        ),
    ]
