# Generated by Django 4.1 on 2022-09-01 14:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0010_alter_chattext_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresult",
            name="chat_id",
            field=models.PositiveBigIntegerField(help_text="chat id"),
        ),
        migrations.AlterField(
            model_name="queryresult",
            name="from_user_id",
            field=models.PositiveBigIntegerField(help_text="message author id"),
        ),
        migrations.AlterField(
            model_name="queryresult",
            name="message_id",
            field=models.PositiveBigIntegerField(help_text="message id"),
        ),
    ]
