name: search gitflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull-build-restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: ${{ secrets.AZURE_PORT }}
          script: |
            cd /home/ks/tg_search
            sudo git pull
            sudo docker-compose build 
            sudo docker-compose down 
            sudo docker-compose up -d
