name: search gitflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull-build-restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/tg_search
            ls -la
            eval `ssh-agent`
            ssh-add ~/.ssh/id_timeweb
            git pull
            sudo docker-compose build
            sudo docker-compose down
            sudo docker-compose up -d
